### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gsalaman**
Let the world know about me.

### CODE REVIEW

**Review by jeffellenbogen — CHANGES_REQUESTED** [review]
Glenn, you are an inspiration. I appreciate you! You are awesome. Come on change this to be more positive.

**Comment by gsalaman** [comment]
Comments incorporated.

**Review by jeffellenbogen — APPROVED** [review]
Much better, Glenn

**Comment by jeffellenbogen** [comment]
Merge this stuff

**Pull request merged**
